---
title: "R Notebook"
output: html_notebook
---
1)
```{r}
library(tidyverse)
library(infer)
library(janitor)

house_sales <- read_csv("data/ames.csv") %>%
  clean_names()
```

2) The data has a right skew, but is on the normal side of things.
```{r}
house_sales %>%
  ggplot() + 
  aes(x = lot_area) +
  geom_histogram(col = "white")
```

3)

```{r}
population_mean <- house_sales %>%
  summarise(mean = mean(lot_area))

bootstrap_1000 <- house_sales %>%
    specify(response = lot_area) %>%
    generate(reps = 1000, type = "bootstrap") %>%
    calculate(stat = "mean") 
```

4)
```{r}
  bootstrap_ci_95 <- bootstrap_1000 %>%
    get_ci(level = 0.95, type = "percentile")
```

5) It's a wider CI as more of our data falls within 99% of the spread than 95%.
```{r}
bootstrap_ci_99 <- bootstrap_1000 %>%
    get_ci(level = 0.99, type = "percentile")

bootstrap_1000 %>%
  visualise(bins = 30) +
  shade_ci(endpoints = bootstrap_ci_99)
```

6)
```{r}
bootstrap_mean <- bootstrap_1000 %>%
  summarise(mean = mean(stat))
``` 

